export const ragExperienceCopy = {
  en: {
    eyebrow: "Engineering, in the open",
    heading: "Retrieval, with the decisions exposed.",
    intro: "Tune the retrieval policy. Watch the evidence change. Inspect every decision.",
    question: "01 / Ask", rank: "02 / Rank", assemble: "03 / Assemble",
    controls: "Retrieval policy", live: "Changes apply instantly to the last search.",
    topK: "Maximum sources", threshold: "Minimum match score", budget: "Context budget",
    chars: "characters", reset: "Reset policy", missing: "Missing information",
    missingQuery: "What are the hourly consulting rates?",
    lastQuery: "Showing evidence for", pending: "Your question changed. Retrieve context to apply it.",
    kept: "sources kept", matched: "sources matched", comparison: "Compared with baseline",
    baseline: "Baseline: up to 3 matching sources, no score cutoff, 1,200 characters.",
    difference: "sources removed", unchanged: "Same sources as baseline", newSources: "sources added",
    inspect: "Inspect a source", corpus: "Seven public chunks · one topic per chunk · English + Khmer",
    score: "Match score", scoreNote: "A keyword score, not a probability of correctness.",
    formula: "80% term coverage + 5% per occurrence (up to 4), capped at 99%.",
    sourceSize: "Source + citation size",
    coverage: "Query terms matched", occurrences: "Matching occurrences", inspectHint: "Select a ranked source to see the text and why it was kept or rejected.",
    preview: "Evidence-backed preview", excerpt: "Exact source excerpts; no model-generated answer.",
    abstain: "There isn’t enough selected evidence to answer.",
    noMatchHint: "The corpus has no matching terms. Try another question; changing the policy cannot invent evidence.",
    filteredHint: "Matching sources exist. Lower the cutoff or increase the context budget to see whether they can be included.",
    emptyTerms: "No searchable terms remain after normalization.",
    prompt: "Inspect the assembled context", contract: "Generation contract", contractText: "Use only the cited context. Cite source IDs for factual claims. If the context does not support the question, say so.",
    tradeoffs: "Why I built it this way", topic: "Small, inspectable chunks", topicText: "Each chunk covers one topic. Whole chunks preserve source meaning; budget packing skips an oversized chunk instead of cutting a sentence.",
    lexical: "An honest retrieval baseline", lexicalText: "Exact word matches make scoring inspectable and avoid matches such as “AI” inside “calling”. They miss synonyms and cross-language meaning. For production, I would evaluate hybrid retrieval against a labeled query set.",
    budgetTitle: "A deliberate evidence budget", budgetText: "A lower cutoff improves recall but admits weaker matches. A small budget keeps context focused but can omit useful evidence. The live trace exposes both tradeoffs.",
    note: "These seven excerpts are curated for this demo. This is not semantic search, a measured accuracy benchmark, or a live LLM call.",
    selected: "In context", noMatch: "No term match", below: "Below cutoff", limit: "Source limit", overBudget: "Budget exceeded",
    queryStep: "Normalized terms", rankStep: "All sources ranked", contextStep: "Cited context", searchStatus: "Retrieving public sources…", ready: "Context updated", baselineCount: "Baseline sources", copy: "Copy context", copied: "Copied", copyFailed: "Select the context text to copy it manually.",
  },
  km: {
    eyebrow: "ការសម្រេចចិត្តវិស្វកម្មដែលអាចមើលឃើញ",
    heading: "ការស្វែងរកដែលអាចពិនិត្យបាន",
    intro: "កែការកំណត់ retrieval។ មើលភស្តុតាងផ្លាស់ប្តូរ និងពិនិត្យការសម្រេចចិត្តនីមួយៗ។",
    question: "01 / សួរ", rank: "02 / រៀបលំដាប់", assemble: "03 / រៀបចំ",
    controls: "ការកំណត់ retrieval", live: "ការកែប្រែអនុវត្តភ្លាមៗលើសំណួរដែលបានស្វែងរកចុងក្រោយ។",
    topK: "ចំនួនប្រភពអតិបរមា", threshold: "ពិន្ទុផ្គូផ្គងអប្បបរមា", budget: "កម្រិត context",
    chars: "តួអក្សរ", reset: "កំណត់ឡើងវិញ", missing: "ព័ត៌មានដែលមិនមាន",
    missingQuery: "What are the hourly consulting rates?",
    lastQuery: "ភស្តុតាងសម្រាប់", pending: "សំណួរបានផ្លាស់ប្តូរ។ សូមស្វែងរក context ដើម្បីអនុវត្ត។",
    kept: "ប្រភពដែលបានជ្រើស", matched: "ប្រភពដែលត្រូវគ្នា", comparison: "ប្រៀបធៀបនឹង baseline",
    baseline: "Baseline៖ ប្រភពត្រូវគ្នារហូតដល់ ៣ គ្មានកម្រិតពិន្ទុ និង ១២០០ តួអក្សរ។",
    difference: "ប្រភពត្រូវបានដកចេញ", unchanged: "ប្រភពដូច baseline", newSources: "ប្រភពបន្ថែម",
    inspect: "ពិនិត្យប្រភព", corpus: "៧ chunk សាធារណៈ · មួយប្រធានបទក្នុងមួយ chunk · អង់គ្លេស + ខ្មែរ",
    score: "ពិន្ទុផ្គូផ្គង", scoreNote: "ជាពិន្ទុពាក្យគន្លឹះ មិនមែនប្រូបាប៊ីលីតេនៃភាពត្រឹមត្រូវទេ។",
    formula: "៨០% នៃការគ្របដណ្តប់ពាក្យ + ៥% ក្នុងមួយដងដែលត្រូវគ្នា (រហូតដល់ ៤) កំណត់ត្រឹម ៩៩%។",
    sourceSize: "ទំហំប្រភព និង citation",
    coverage: "ពាក្យសំណួរដែលត្រូវគ្នា", occurrences: "ចំនួនដងដែលត្រូវគ្នា", inspectHint: "ជ្រើសប្រភព ដើម្បីមើលអត្ថបទ និងមូលហេតុនៃការជ្រើសឬដកចេញ។",
    preview: "ភស្តុតាងសម្រាប់ចម្លើយ", excerpt: "អត្ថបទដើមពីប្រភព មិនមែនចម្លើយដែលបង្កើតដោយ model ទេ។",
    abstain: "ភស្តុតាងដែលបានជ្រើសមិនគ្រប់គ្រាន់សម្រាប់ចម្លើយទេ។",
    noMatchHint: "គ្មានពាក្យដែលត្រូវគ្នាក្នុងសំណុំឯកសារ។ សាកល្បងសំណួរផ្សេង ការកែការកំណត់មិនអាចបង្កើតភស្តុតាងបានទេ។",
    filteredHint: "មានប្រភពត្រូវគ្នា។ បន្ថយកម្រិតពិន្ទុ ឬបង្កើនកម្រិត context ដើម្បីសាកល្បងជ្រើសវា។",
    emptyTerms: "គ្មានពាក្យដែលអាចស្វែងរកក្រោយការធ្វើស្តង់ដារ។",
    prompt: "ពិនិត្យ context ដែលបានរៀបចំ", contract: "កិច្ចព្រមព្រៀងសម្រាប់ generation", contractText: "ប្រើតែ context ដែលមានប្រភព។ ដាក់ ID ប្រភពសម្រាប់ការអះអាង។ បើ context មិនគាំទ្រសំណួរ សូមប្រាប់ថាមិនមានភស្តុតាង។",
    tradeoffs: "មូលហេតុនៃការរចនានេះ", topic: "Chunk តូចដែលអាចពិនិត្យបាន", topicText: "Chunk នីមួយៗមានមួយប្រធានបទ។ ការរក្សា chunk ទាំងមូលការពារអត្ថន័យប្រភព ហើយរំលង chunk ដែលធំពេក ជំនួសការកាត់ប្រយោគ។",
    lexical: "Baseline ដែលអាចពន្យល់បាន", lexicalText: "ការផ្គូផ្គងពាក្យពេញធ្វើឱ្យពិន្ទុអាចពិនិត្យបាន និងមិនរាប់ “AI” ក្នុង “calling”។ វាមិនយល់ពាក្យមានន័យដូចគ្នា ឬអត្ថន័យឆ្លងភាសាទេ។ សម្រាប់ប្រព័ន្ធពិត ខ្ញុំនឹងវាយតម្លៃ hybrid retrieval ជាមួយសំណួរដែលមានស្លាកចម្លើយ។",
    budgetTitle: "កម្រិតភស្តុតាងដែលមានគោលបំណង", budgetText: "កម្រិតពិន្ទុទាបអាចរកឃើញប្រភពច្រើន តែមានការផ្គូផ្គងខ្សោយ។ កម្រិត context តូចរក្សាការផ្តោត តែអាចបាត់ភស្តុតាងមានប្រយោជន៍។ Trace បង្ហាញផលប៉ះពាល់ទាំងពីរ។",
    note: "អត្ថបទទាំង ៧ ត្រូវបានជ្រើសសម្រាប់ demo។ នេះមិនមែន semantic search ការវាស់ភាពត្រឹមត្រូវ ឬការហៅ LLM ទេ។",
    selected: "ក្នុង context", noMatch: "គ្មានពាក្យត្រូវគ្នា", below: "ក្រោមកម្រិតពិន្ទុ", limit: "កម្រិតចំនួនប្រភព", overBudget: "លើសកម្រិត context",
    queryStep: "ពាក្យដែលបានធ្វើស្តង់ដារ", rankStep: "ប្រភពទាំងអស់តាមលំដាប់", contextStep: "Context មានប្រភព", searchStatus: "កំពុងស្វែងរកប្រភពសាធារណៈ…", ready: "Context បានធ្វើបច្ចុប្បន្នភាព", baselineCount: "ប្រភព baseline", copy: "ចម្លង context", copied: "បានចម្លង", copyFailed: "ជ្រើសអត្ថបទ context ដើម្បីចម្លងដោយខ្លួនឯង។",
  },
} as const;
